Add priority
santalvarez/swift-rule-engine pull request #16
Opened 2024-09-09 14:12 UTC by ismailgulek

Added `priority` into `Rule`, which was implemented in the [json-rules-engine](https://github.com/CacheControl/json-rules-engine/tree/master).
Documentation is here: https://github.com/CacheControl/json-rules-engine/blob/master/docs/rules.md#methods

2024-09-09 14:13 UTC, ismailgulek commented
@santalvarez it'd be great if you can review and merge this.

2024-09-09 14:51 UTC, santalvarez commented
Hey! Thanks a lot for contributing. I will review it today.

2024-09-11 15:13 UTC, santalvarez requested changes

2024-09-11 15:13 UTC, santalvarez commented on Tests/SwiftRuleEngineTests/RuleEngineTests/RuleEngineDictionaryTests.swift
> +            "name": "test-rule",
I don't think we are testing the priority correctly in this test. To correctly test it the two rules should be identical and the priority of the second one should be higher. Then we test that the second one matched and not the first one so we can make sure that the rules were correctly sorted.
As it is right now the rule 1 will never match even with no priority. Lets make that change and I'll merge

2024-09-11 19:54 UTC, ismailgulek commented on Tests/SwiftRuleEngineTests/RuleEngineTests/RuleEngineDictionaryTests.swift
> +            "name": "test-rule",
That's what I exactly thought but set the priority wrong 🤦‍♂️, updated now

2024-09-12 13:42 UTC, santalvarez commented on Tests/SwiftRuleEngineTests/RuleEngineTests/RuleEngineDictionaryTests.swift
> +            "name": "test-rule",
Great but the rule1 will never match regardless of the priority. You need to make the rule1 's conditions identical to rule2 (replace Lionel with Cristiano on rule1).

2024-09-12 14:00 UTC, ismailgulek commented on Tests/SwiftRuleEngineTests/RuleEngineTests/RuleEngineDictionaryTests.swift
> +            "name": "test-rule",
I see what you mean, updated.

2024-09-12 14:19 UTC, santalvarez approved these changes
Nice!

2024-09-12 14:19 UTC, merged